USE CRM_DEV_SDK


-- Insert unique ID's into new table from DESIGNATIONLEVEL
INSERT INTO USR_UA_DESIGNATIONLEVEL_EXT (DESIGNATIONLEVELID, ADDEDBYID, CHANGEDBYID)
SELECT ID, ADDEDBYID, CHANGEDBYID FROM DESIGNATIONLEVEL 

-- Create temp table to store values for mapping lookup tables
CREATE TABLE #TEMP(
DESIGNATIONLEVELID UNIQUEIDENTIFIER,
DESIGNATIONSTATUS NVARCHAR(255),
PREFERREDSCHOOL NVARCHAR(255),
CONSTITUENTTYPE NVARCHAR(255)
);

-- Insert the designation level ids into temp table for mapping lookup tables
INSERT INTO #TEMP (DESIGNATIONLEVELID)
SELECT DESIGNATIONLEVELID FROM USR_UA_DESIGNATIONLEVEL_EXT

-- Generate guids for lookup table items for PREFERREDCODEID
INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Academic Affairs', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Alumni Affairs', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Auxiliary Services', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Capstone International', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'A&S', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Accountancy', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'MBA', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'C&IS', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'CCHS', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Continuing Studies', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Education', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Engineering', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'HES', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Nursing', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Honors College', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Human Resources', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Law School', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Military Science', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'New College', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'President', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Social Work', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'SLIS', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Student Life', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Student Financial Aid', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Undergraduate Admissions', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'University Advancement', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'University Libraries', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'University Museums', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'C&BA', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Intercollegiate Athletics', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'College of Community Health', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONPREFERREDSCHOOLCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Not Assigned', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57')

-- Generate new guids for lookup table items for DESIGNATIONSTATUSCODEID
INSERT INTO USR_UA_DESIGNATIONSTATUSCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Archived', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONSTATUSCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'In Progress', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONSTATUSCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Stewarded', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONSTATUSCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Testamentary', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONSTATUSCODE (ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Not Assigned', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

-- Generate guids for lookup table items for CONSTITUENTTYPECODE
INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Not Assigned', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Annual Fund', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Chair', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Other Endowed Fund', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Professorship', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Scholarship', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONCONSTITUENTTYPECODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Support Fund', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

INSERT INTO USR_UA_DESIGNATIONDEPARTMENTCODE(ID, DESCRIPTION, ADDEDBYID, CHANGEDBYID)
VALUES (newid(), 'Not Assigned', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57', 'F2B21B0C-CAD9-4AAC-9504-49824E80AE57');

-- Update temp table and set extended column 'status' to the designation level note title.
UPDATE #TEMP SET #TEMP.DESIGNATIONSTATUS = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #TEMP ON #TEMP.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%status%'

-- Update temp table and set extended column 'stewardshipname' to the designation level note title.
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.STEWARDSHIPNAME = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%stewardship name%'

UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.STEWARDSHIPNAME = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%stewarship name%'

UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.STEWARDSHIPNAME = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%sterwardship name%'

-- Update temp table and set extended column 'preferred school' to the designation level note title.
UPDATE #TEMP SET #TEMP.PREFERREDSCHOOL = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #TEMP ON #TEMP.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%preferred school%'

-- Update table and set extended column 'established by' to the designation level note title.
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.ESTABLISHEDBY = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%established by%'

-- Update temp table and set extended column 'constituent type' to the designation level note title.
UPDATE #TEMP SET #TEMP.CONSTITUENTTYPE = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #TEMP ON #TEMP.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%constituent type%'

-- Update table and set extended column 'fund restriction' to the designation level note title.
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.FUNDRESTRICTION = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE = 'fund restriction'

-- Update table and set extended column 'MOA date' to the designation level note title.
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.MOADATE = dbo.DESIGNATIONLEVELNOTE.DATEENTERED FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%MOA Date%'

-- Update table and set extended column 'resolution date' to the designation level note title.
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET USR_UA_DESIGNATIONLEVEL_EXT.RESOLUTIONDATE = dbo.DESIGNATIONLEVELNOTE.DATEENTERED FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN USR_UA_DESIGNATIONLEVEL_EXT ON USR_UA_DESIGNATIONLEVEL_EXT.DESIGNATIONLEVELID = DBO.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%resolution%'

-- Update existing records with newly generated guids in lookup table for DESIGNATIONSTATUSCODEID
UPDATE dle
SET DESIGNATIONSTATUSCODEID = (SELECT ID FROM USR_UA_DESIGNATIONSTATUSCODE WHERE DESCRIPTION LIKE '%Archived%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.DESIGNATIONSTATUS LIKE '%Archived%'

UPDATE dle
SET DESIGNATIONSTATUSCODEID = (SELECT ID FROM USR_UA_DESIGNATIONSTATUSCODE WHERE DESCRIPTION LIKE '%In Progress%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.DESIGNATIONSTATUS LIKE '%In Progress%'

UPDATE dle
SET DESIGNATIONSTATUSCODEID = (SELECT ID FROM USR_UA_DESIGNATIONSTATUSCODE WHERE DESCRIPTION LIKE '%Stewarded%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.DESIGNATIONSTATUS LIKE '%Stewarded%'

UPDATE dle
SET DESIGNATIONSTATUSCODEID = (SELECT ID FROM USR_UA_DESIGNATIONSTATUSCODE WHERE DESCRIPTION LIKE '%Testamentary%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.DESIGNATIONSTATUS LIKE '%Testamentary%'

UPDATE USR_UA_DESIGNATIONLEVEL_EXT 
SET DESIGNATIONSTATUSCODEID = (SELECT ID FROM USR_UA_DESIGNATIONSTATUSCODE WHERE DESCRIPTION LIKE '%Not Assigned%')
WHERE DESIGNATIONSTATUSCODEID IS NULL

-- Update all records with guids for PREFERREDSCHOOLCODE
UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Academic Affairs%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Academic Affairs%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Alumni Affairs%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Alumni Affairs%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Auxiliary Services%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Auxiliary Services%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Capstone International%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Capstone International%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%A&S%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%A&S%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Accountancy%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Accountancy%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%MBA%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%MBA%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%C&IS%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%C&IS%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%CCHS%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%CCHS%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Continuing Studies%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Continuing Studies%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Education%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Education%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Engineering%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Engineering%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%HES%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%HES%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Nursing%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Nursing%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Honors College%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Honors College%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Human Resources%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Human Resources%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Law School%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Law School%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%MBA%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL = '%Law%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%School of Law%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%School of Law%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Military Science%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Military Science%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%New College%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%New College%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%President%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%President%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Social Work%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Social Work%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%SLIS%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%SLIS%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Student Life%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Student Life%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Student Financial Aid%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Student Financial Aid%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Undergraduate Admissions%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Undergraduate Admissions%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%MBA%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%General University%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%University Advancement%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%University Advacement%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%University Libraries%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%University Libraries%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%University Museums%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%University Museums%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%C&BA%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%C&BA%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Intercollegiate Athletics%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%Intercollegiate Athletics%'

UPDATE dle
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%College of Community Health%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.PREFERREDSCHOOL LIKE '%College of Community Health%'

UPDATE USR_UA_DESIGNATIONLEVEL_EXT 
SET PREFERREDSCHOOLCODEID = (SELECT ID FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE DESCRIPTION LIKE '%Not Assigned%')
WHERE PREFERREDSCHOOLCODEID IS NULL

-- Update constituent type ids
UPDATE dle
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Annual Fund%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.CONSTITUENTTYPE LIKE '%Annual Fund%'

UPDATE dle
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Chair%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.CONSTITUENTTYPE LIKE '%Chair%'

UPDATE dle
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Other Endowed Fund%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.CONSTITUENTTYPE LIKE '%Other Endowed Fund%'

UPDATE dle
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Professorship%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.CONSTITUENTTYPE LIKE '%Professorship%'

UPDATE dle
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Scholarship%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.CONSTITUENTTYPE LIKE '%Scholarship%'

UPDATE dle
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Support Fund%')
FROM USR_UA_DESIGNATIONLEVEL_EXT dle
JOIN #TEMP ON dle.DESIGNATIONLEVELID = #TEMP.DESIGNATIONLEVELID
WHERE #TEMP.CONSTITUENTTYPE LIKE '%Support Fund%'

UPDATE USR_UA_DESIGNATIONLEVEL_EXT 
SET CONSTITUENTTYPECODEID = (SELECT ID FROM USR_UA_DESIGNATIONCONSTITUENTTYPECODE WHERE DESCRIPTION LIKE '%Not Assigned%')
WHERE CONSTITUENTTYPECODEID IS NULL

-- Update fundmanager with random guid because fund manager search function requires one
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET FUNDMANAGERID=newid()

-- Set all departments to Not Assigned
UPDATE USR_UA_DESIGNATIONLEVEL_EXT 
SET DEPARTMENTCODEID = (SELECT ID FROM USR_UA_DESIGNATIONDEPARTMENTCODE WHERE DESCRIPTION LIKE '%Not Assigned%')
WHERE DEPARTMENTCODEID IS NULL

-- Clean up fund restriction
UPDATE USR_UA_DESIGNATIONLEVEL_EXT
SET FUNDRESTRICTION=LTRIM(REPLACE([FUNDRESTRICTION],'Comments:','')) 
FROM USR_UA_DESIGNATIONLEVEL_EXT
WHERE FUNDRESTRICTION like '%Comments:%'

UPDATE USR_UA_DESIGNATIONLEVEL_EXT
SET FUNDRESTRICTION=LTRIM(REPLACE([FUNDRESTRICTION],'NOTE:','')) 
FROM USR_UA_DESIGNATIONLEVEL_EXT
WHERE FUNDRESTRICTION like '%NOTE:%'


-- Cleanup operations
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET STEWARDSHIPNAME = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(STEWARDSHIPNAME, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET ESTABLISHEDBY = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(ESTABLISHEDBY, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET FUNDRESTRICTION = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(FUNDRESTRICTION, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET FUNDRESTRICTION = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(FUNDRESTRICTION, ' ','<>'),'><',''),'<>',' ')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET ESTABLISHEDBY = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(ESTABLISHEDBY, ' ','<>'),'><',''),'<>',' ')))


DROP TABLE #TEMP



