UPDATE dbo.DESIGNATIONLEVELNOTE SET TEXTNOTE = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(TEXTNOTE, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))

UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET STEWARDSHIPNAME = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(STEWARDSHIPNAME, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET ESTABLISHEDBY = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(ESTABLISHEDBY, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET CONSTITUENTTYPE = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CONSTITUENTTYPE, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))
UPDATE USR_UA_DESIGNATIONLEVEL_EXT SET FUNDRESTRICTION = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(FUNDRESTRICTION, CHAR(9), ''), CHAR(13), ''), CHAR(10), '')))

-- Designation Note
CREATE TABLE #ETL (
DESIGNATIONLEVELID uniqueidentifier,
NAME varchar(255),
STATUS varchar(255),
STEWARDSHIP_NAME varchar(255),
PREFERRED_SCHOOL varchar(255),
ESTABLISHED_BY varchar(500),
CONSTITUENT_TYPE varchar(255),
FUND_RESTRICTION nvarchar(MAX),
MOA_DATE DATE,
RESOLUTION_DATE DATE)


INSERT INTO #ETL (DESIGNATIONLEVELID) SELECT DESIGNATIONLEVELID FROM USR_UA_DESIGNATIONLEVEL_EXT

UPDATE #ETL SET NAME = dl.NAME FROM dbo.DESIGNATIONLEVEL AS dl WHERE #ETL.DESIGNATIONLEVELID = dl.ID

UPDATE #ETL SET STATUS = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%status%'

UPDATE #ETL SET STEWARDSHIP_NAME = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%stewardship name%'

UPDATE #ETL SET PREFERRED_SCHOOL = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%preferred school%'

UPDATE #ETL SET ESTABLISHED_BY = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%established by%'

UPDATE #ETL SET CONSTITUENT_TYPE = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%constituent type%'

UPDATE #ETL SET FUND_RESTRICTION = dbo.DESIGNATIONLEVELNOTE.TEXTNOTE FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%fund restriction%'

UPDATE #ETL SET MOA_DATE = dbo.DESIGNATIONLEVELNOTE.DATEENTERED FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%MOA date%'

UPDATE #ETL SET RESOLUTION_DATE = dbo.DESIGNATIONLEVELNOTE.DATEENTERED FROM DBO.DESIGNATIONLEVELNOTE 
INNER JOIN #ETL ON #ETL.DESIGNATIONLEVELID = dbo.DESIGNATIONLEVELNOTE.DESIGNATIONLEVELID
WHERE DBO.DESIGNATIONLEVELNOTE.TITLE LIKE '%resolution%'


SELECT DISTINCT
etl.NAME,
etl.STATUS AS OLD_STATUS,
(SELECT DESCRIPTION FROM USR_UA_DESIGNATIONSTATUSCODE WHERE ID=dle.DESIGNATIONSTATUSCODEID) AS NEW_STATUS,
etl.STEWARDSHIP_NAME AS OLD_STEWARDSHIP_NAME,
dle.STEWARDSHIPNAME AS NEW_STEWARDSHIP_NAME,
etl.PREFERRED_SCHOOL AS OLD_PREFERRRDSCHOOL,
(SELECT DESCRIPTION FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE ID=dle.PREFERREDSCHOOLCODEID) AS NEW_PREFFERED_SCHOOL,
etl.ESTABLISHED_BY AS OLD_ESTABLISHEDBY,
dle.ESTABLISHEDBY AS NEW_ESTABLISHEDBY,
etl.CONSTITUENT_TYPE AS OLD_CONSTITUENTTYPE,
dle.CONSTITUENTTYPE AS NEW_CONSTITUENTTYPE,
etl.FUND_RESTRICTION AS OLD_FUNDRESTRICTION,
dle.FUNDRESTRICTION AS NEW_FUNDRESTRICTION,
etl.MOA_DATE AS OLD_MOA_DATE,
dle.MOADATE AS NEW_MOA_DATE,
etl.RESOLUTION_DATE AS OLD_RESOLUTION_DATE,
dle.RESOLUTIONDATE AS NEW_RESOLUTION_DATE,
CASE 
	WHEN 
	etl.PREFERRED_SCHOOL LIKE (SELECT DESCRIPTION FROM USR_UA_DESIGNATIONPREFERREDSCHOOLCODE WHERE ID=dle.PREFERREDSCHOOLCODEID)
	THEN 'No Change'
	ELSE 'Change' END as ChangeFlag
FROM #ETL AS etl
JOIN USR_UA_DESIGNATIONLEVEL_EXT AS dle ON etl.DESIGNATIONLEVELID = dle.DESIGNATIONLEVELID
WHERE etl.PREFERRED_SCHOOL IS NOT NULL  AND etl.FUND_RESTRICTION IS NOT NULL
ORDER BY ChangeFlag ASC

DROP TABLE #ETL
